# Site

theme: jekyll-theme-cayman
title: Closed-loop Control Mashine Learning
description: On this web page you can find litreture review of topic related papers


#url:                http://cognition.uni-osnabrueck.de/CLCML/
#baseurl:            "neuroinfo-os/CLCML"

# Jekyll
#permalink:          /:title/
#markdown:           kramdown
#highlighter:        rouge
#kramdown:
 # auto_ids:         true
  #footnote_nr:      1
  #entity_output:    as_char
  #toc_levels:       1..6
  #enable_coderay:   false
#mathjax:            true
#sass:
 # sass_dir:         _sass
  #style:            compressed

# Comments
#disqus_shortname:   taylantatli

# Social
# if you don't have any of social below, comment the line.
#google:
  #plus:            #username
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
#email:
#twitter:            username
#facebook:           username
github-url:         username
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
#linkedin:          username
#xing:              username
#instagram:          username
#lastfm:            username
#tumblr:            username
#medium:            '@username'
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
#youtube:           username
#youtube-channel:   channel
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username
#plugins:
 # - jekyll-relative-links
#relative_links:
 # enabled: true
  #collections: true
#include:
  - README.md
 

#defaults:
  # _docs
 # - scope:
  #    path: ""
   #   type: docs
    #values:
     # sidebar:
      #  nav: "docs"

# Gems
#gems:
 # - jekyll-mentions
  #- jekyll-feed
  #- jekyll-sitemap
  #- jekyll-gist

#jekyll-mentions:
    #base_url: https://github.com

# Exclude list
#exclude:




