theme: minima
title: HOME
author:
  name: GitHub User
  email: your-email@domain.com
#subtitle: 
#description: On this web page you can find literature review of topic related papers
#baseurl: 'CLCML/docs'

# --- List of links in the navigation bar --- #

header_pages:
  -  introduction.md
  -  literature_review.md
  -  useful_sources.md

 
 
